from enum import Enum


class ConfigKey(str, Enum):
    AUDIO_TEMP_PATH = "AUDIO_TEMP_PATH"
    APP_ENVIRONMENT = "APP_ENVIRONMENT"
    APP_NAME = "APP_NAME"
    APP_PERSISTENT_USER_SETTINGS_ENABLED = "APP_PERSISTENT_USER_SETTINGS_ENABLED"
    APP_PUSH_TRANSLATED_TEXT_AUDIO_ENABLED = "APP_PUSH_TRANSLATED_TEXT_AUDIO_ENABLED"
